// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwiuuyincxtkvhhebfum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3aXV1eWluY3h0a3ZoaGViZnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mjg3NTYsImV4cCI6MjA2NDUwNDc1Nn0.yUtcj_NPpZs8nRYzMYxOaFRd1x81mrAg0JE6czBlWpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);